changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixed
      labels:
        - bug
    - title: Documentations
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
